### ISSUE TITLE
Robtop sucks

### ISSUE THREAD

**Issue by onezpp** [ImmediateMurderProfessionals/My-gd-account-is-banned-this-is-literally-1984#1]
Robtop is an assholt why did he ban you

**Comment by onezpp** [comment]
You edited my message to match the status quo of the Bombcraft state. As the new chairman of the People's Organization of H-Frictions, you will be displaced by a revolution in 12 days.

**Comment by ImmediateMurderProfessionals** [comment]
Can you overthrow Hexagon first? He’s the salty little crotch goblin who mass reported my levels and got me false banned

**Comment by ImmediateMurderProfessionals** [comment]
imma speedrun failing nnn

**Comment by ImmediateMurderProfessionals** [comment]
pinging you

**Comment by ImmediateMurderProfessionals** [comment]
> You edited my message to match the status quo of the Bombcraft state. As the new chairman of the People's Organization of H-Frictions, you will be displaced by a revolution in 12 days.

it's been 22 days where the fuck is the revolution

**Comment by ImmediateMurderProfessionals** [comment]
q

**Comment by ImmediateMurderProfessionals** [comment]
not banned lol
